//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.14 at 09:25:28 PM MSK 
//


package com.xledbd.clients;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for citizenship.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="citizenship"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BELARUS"/&gt;
 *     &lt;enumeration value="LATVIA"/&gt;
 *     &lt;enumeration value="LITHUANIA"/&gt;
 *     &lt;enumeration value="POLAND"/&gt;
 *     &lt;enumeration value="RUSSIA"/&gt;
 *     &lt;enumeration value="UKRAINE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "citizenship")
@XmlEnum
public enum Citizenship {

    BELARUS,
    LATVIA,
    LITHUANIA,
    POLAND,
    RUSSIA,
    UKRAINE;

    public String value() {
        return name();
    }

    public static Citizenship fromValue(String v) {
        return valueOf(v);
    }

}
