//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.14 at 09:25:28 PM MSK 
//


package com.xledbd.clients;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.util.Date;


/**
 * <p>Java class for client complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="client"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="middlename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="passportSeries" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="passportNumber"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="^[0-9]{7}$"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cityOfResidence" type="{http://localhost/clients}city"/&gt;
 *         &lt;element name="addressOfResidence" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cellphoneNumber"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="^\+375-[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}$"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isEmployed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cityOfRegistration" type="{http://localhost/clients}city"/&gt;
 *         &lt;element name="citizenship" type="{http://localhost/clients}citizenship"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "client", propOrder = {
    "lastname",
    "firstname",
    "middlename",
    "dateOfBirth",
    "passportSeries",
    "passportNumber",
    "cityOfResidence",
    "addressOfResidence",
    "cellphoneNumber",
    "email",
    "isEmployed",
    "position",
    "cityOfRegistration",
    "citizenship"
})
@Entity
@Table(name = "client")
public class Client implements Serializable {

    @XmlTransient
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @XmlElement(required = true)
    @Column(name = "lastname")
    protected String lastname;

    @XmlElement(required = true)
    @Column(name = "firstname")
    protected String firstname;

    @XmlElement(required = true)
    @Column(name = "middlename")
    protected String middlename;

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @Column(name = "dateOfBirth")
    protected Date dateOfBirth;

    @XmlElement(required = true)
    @Column(name = "passportSeries")
    protected String passportSeries;

    @XmlElement(required = true)
    @Column(name = "passportNumber")
    protected String passportNumber;

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    @Column(name = "cityOfResidence")
    protected City cityOfResidence;

    @XmlElement(required = true)
    @Column(name = "addressOfResidence")
    protected String addressOfResidence;

    @XmlElement
    @Column(name = "cellphoneNumber")
    protected String cellphoneNumber;

    @XmlElement
    @Column(name = "email")
    protected String email;

    @XmlElement
    @Column(name = "isEmployed")
    protected boolean isEmployed;

    @XmlElement
    @Column(name = "position")
    protected String position;

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    @Column(name = "cityOfRegistration")
    protected City cityOfRegistration;

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    @Column(name = "citizenship")
    protected Citizenship citizenship;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public boolean isEmployed() {
        return isEmployed;
    }

    public void setEmployed(boolean employed) {
        isEmployed = employed;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the middlename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddlename() {
        return middlename;
    }

    /**
     * Sets the value of the middlename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddlename(String value) {
        this.middlename = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDateOfBirth(Date value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the passportSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportSeries() {
        return passportSeries;
    }

    /**
     * Sets the value of the passportSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportSeries(String value) {
        this.passportSeries = value;
    }

    /**
     * Gets the value of the passportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * Sets the value of the passportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportNumber(String value) {
        this.passportNumber = value;
    }

    /**
     * Gets the value of the cityOfResidence property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCityOfResidence() {
        return cityOfResidence;
    }

    /**
     * Sets the value of the cityOfResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCityOfResidence(City value) {
        this.cityOfResidence = value;
    }

    /**
     * Gets the value of the addressOfResidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressOfResidence() {
        return addressOfResidence;
    }

    /**
     * Sets the value of the addressOfResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressOfResidence(String value) {
        this.addressOfResidence = value;
    }

    /**
     * Gets the value of the cellphoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellphoneNumber() {
        return cellphoneNumber;
    }

    /**
     * Sets the value of the cellphoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellphoneNumber(String value) {
        this.cellphoneNumber = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the isEmployed property.
     * 
     */
    public boolean isIsEmployed() {
        return isEmployed;
    }

    /**
     * Sets the value of the isEmployed property.
     * 
     */
    public void setIsEmployed(boolean value) {
        this.isEmployed = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the cityOfRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCityOfRegistration() {
        return cityOfRegistration;
    }

    /**
     * Sets the value of the cityOfRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCityOfRegistration(City value) {
        this.cityOfRegistration = value;
    }

    /**
     * Gets the value of the citizenship property.
     * 
     * @return
     *     possible object is
     *     {@link Citizenship }
     *     
     */
    public Citizenship getCitizenship() {
        return citizenship;
    }

    /**
     * Sets the value of the citizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citizenship }
     *     
     */
    public void setCitizenship(Citizenship value) {
        this.citizenship = value;
    }

}
